In [1]:
import wfdb
import pandas as pd
record = wfdb.rdrecord('/Users/dogukankorkut/Library/CloudStorage/OneDrive-ozyegin.edu.tr/Ozyegin_MSc_Thesis/04_Technical_Works/ECG_Datasets/01_Ningbo/01_Database_PyhsioNet/JS00001')  # Örneğin 'JS00001' dosyasını okuma

In [2]:
header_info = record.__dict__
header_info

{'record_name': 'JS00001',
 'n_sig': 12,
 'fs': 500,
 'counter_freq': None,
 'base_counter': None,
 'sig_len': 5000,
 'base_time': None,
 'base_date': None,
 'comments': ['Age: 85',
  'Sex: Male',
  'Dx: 164889003,59118001,164934002',
  'Rx: Unknown',
  'Hx: Unknown',
  'Sx: Unknown'],
 'sig_name': ['I',
  'II',
  'III',
  'aVR',
  'aVL',
  'aVF',
  'V1',
  'V2',
  'V3',
  'V4',
  'V5',
  'V6'],
 'p_signal': array([[-0.254,  0.264,  0.517, ...,  0.81 ,  0.81 ,  0.527],
        [-0.254,  0.264,  0.517, ...,  0.81 ,  0.81 ,  0.527],
        [-0.254,  0.264,  0.517, ...,  0.81 ,  0.81 ,  0.527],
        ...,
        [-0.034, -0.068, -0.034, ..., -0.205, -0.2  ,  0.102],
        [ 0.024, -0.049, -0.073, ..., -0.2  , -0.195,  0.093],
        [ 0.005, -0.034, -0.039, ..., -0.171, -0.166,  0.112]]),
 'd_signal': None,
 'e_p_signal': None,
 'e_d_signal': None,
 'file_name': ['JS00001.mat',
  'JS00001.mat',
  'JS00001.mat',
  'JS00001.mat',
  'JS00001.mat',
  'JS00001.mat',
  'JS00001.mat',
  '

In [3]:
record_name = record.record_name
print(record_name)
print(type(record_name))

JS00001
<class 'str'>


In [4]:
comments = record.comments
print(comments)
print(type(comments))

['Age: 85', 'Sex: Male', 'Dx: 164889003,59118001,164934002', 'Rx: Unknown', 'Hx: Unknown', 'Sx: Unknown']
<class 'list'>


In [5]:
sig_name = record.sig_name
print(sig_name)
print(type(sig_name))

['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']
<class 'list'>


In [6]:
p_signal = record.p_signal
print(p_signal)
print(type(p_signal))

[[-0.254  0.264  0.517 ...  0.81   0.81   0.527]
 [-0.254  0.264  0.517 ...  0.81   0.81   0.527]
 [-0.254  0.264  0.517 ...  0.81   0.81   0.527]
 ...
 [-0.034 -0.068 -0.034 ... -0.205 -0.2    0.102]
 [ 0.024 -0.049 -0.073 ... -0.2   -0.195  0.093]
 [ 0.005 -0.034 -0.039 ... -0.171 -0.166  0.112]]
<class 'numpy.ndarray'>
